-- MySQL Script generated by MySQL Workbench
-- Sat Feb 17 21:28:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto` DEFAULT CHARACTER SET utf8 ;
USE `Proyecto` ;

-- -----------------------------------------------------
-- Table `Proyecto`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Numerotelefono` VARCHAR(45) NOT NULL,
  `CorreoElectronico` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_Usuarios_Departamento1_idx` (`Departamento_idDepartamento` ASC),
  CONSTRAINT `fk_Usuarios_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `Proyecto`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`videosencontrados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`videosencontrados` (
  `idvideosencontrados` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvideosencontrados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`Videonoencontrados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`Videonoencontrados` (
  `idVideoNoEncontrados` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idVideoNoEncontrados`),
  INDEX `fk_Videonoencontrados_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  CONSTRAINT `fk_Videonoencontrados_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Proyecto`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`VideosVistos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`VideosVistos` (
  `idVideos_Vistos` INT NOT NULL AUTO_INCREMENT,
  `videosencontrados_idvideosencontrados` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idVideos_Vistos`),
  INDEX `fk_Videos Vistos_videosencontrados1_idx` (`videosencontrados_idvideosencontrados` ASC),
  INDEX `fk_VideosVistos_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  CONSTRAINT `fk_Videos Vistos_videosencontrados1`
    FOREIGN KEY (`videosencontrados_idvideosencontrados`)
    REFERENCES `Proyecto`.`videosencontrados` (`idvideosencontrados`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VideosVistos_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Proyecto`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto`.`cargos` (
  `idcargos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idcargos`),
  INDEX `fk_cargos_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  CONSTRAINT `fk_cargos_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Proyecto`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
